### PR TITLE
I am interested in using your game on my website. Could you add a license file like the MIT one in this pull request so I know how you want your software used?

### PR DESCRIPTION
**Pull request by jpbida**

### CODE REVIEW

**Comment by sbordes** [comment]
I will a add the same license as JRebirth Apache V2 instead of MIT.

You can use the application on you site if you put a simple link to JRebirth homesite

**Comment by jpbida** [comment]
Thanks! This is the homesite: http://www.jrebirth.org/ ?

Best,

~Jp

**Comment by sbordes** [comment]
Yes you can point to http://www.jrebirth.org/apps/MasteringTables.html to track new versions.

**Comment by jpbida** [comment]
Thanks!

**Pull request closed without merging**
